--DROP TABLE IF EXISTS "AppointmentHistory", "WorkOrders", "OrderItems", "Orders", "Parts", "Suppliers",
--"AppointmentMedia", "Appointments", "Vehicles", "Calendar", "Users", "PriceHistory" CASCADE;


CREATE TABLE IF NOT EXISTS "Users" (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "email" VARCHAR UNIQUE NOT NULL,
                                       "password_hash" VARCHAR NOT NULL,
                                       "first_name" VARCHAR,
                                       "last_name" VARCHAR,
                                       "phone" VARCHAR,
                                       "role" VARCHAR,
                                       "created_at" TIMESTAMP DEFAULT now(),
    "updated_at" TIMESTAMP DEFAULT now()
    );
COMMENT ON COLUMN "Users"."role" IS 'ENUM: ''client'', ''admin''';

-- Vehicles Table
CREATE TABLE IF NOT EXISTS"Vehicles" (
                                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "user_id" INTEGER,
                                         "vehicle_type" VARCHAR,
                                         "brand" VARCHAR,
                                         "model" VARCHAR,
                                         "year" INTEGER,
                                         "is_electric" BOOLEAN DEFAULT false,
                                         "notes" TEXT,
                                         "created_at" TIMESTAMP DEFAULT now()
    );
COMMENT ON COLUMN "Vehicles"."vehicle_type" IS 'ENUM: ''motocicleta'', ''bicicleta'', ''trotineta''';

-- Appointments Table
CREATE TABLE IF NOT EXISTS "Appointments" (
                                              "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "user_id" INTEGER,
                                              "vehicle_id" INTEGER,
                                              "appointment_date" TIMESTAMP NOT NULL,
                                              "status" VARCHAR,
                                              "problem_description" TEXT,
                                              "admin_response" TEXT,
                                              "estimated_price" DECIMAL,
                                              "estimated_completion_time" TIMESTAMP,
                                              "warranty_info" TEXT,
                                              "created_at" TIMESTAMP DEFAULT now(),
    "updated_at" TIMESTAMP DEFAULT now()
    );
COMMENT ON COLUMN "Appointments"."status" IS 'ENUM: ''pending'', ''approved'', ''rejected'', ''completed'', ''cancelled''';

-- AppointmentMedia Table
CREATE TABLE IF NOT EXISTS "AppointmentMedia" (
                                                  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  "appointment_id" INTEGER,
                                                  "file_path" VARCHAR NOT NULL,
                                                  "file_type" VARCHAR,
                                                  "original_filename" VARCHAR,
                                                  "mime_type" VARCHAR,
                                                  "uploaded_at" TIMESTAMP DEFAULT now()
    );
COMMENT ON COLUMN "AppointmentMedia"."file_type" IS 'ENUM: ''image'', ''video''';

-- Parts Table
CREATE TABLE IF NOT EXISTS "Parts" (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "name" VARCHAR NOT NULL,
                                       "description" TEXT,
                                       "part_number" VARCHAR UNIQUE,
                                       "category" VARCHAR,
                                       "price" DECIMAL NOT NULL,
                                       "stock_quantity" INTEGER DEFAULT 0,
                                       "minimum_stock_level" INTEGER DEFAULT 5,
                                       "supplier_id" INTEGER,
                                       "created_at" TIMESTAMP DEFAULT now(),
    "updated_at" TIMESTAMP DEFAULT now()
    );

-- Suppliers Table
CREATE TABLE IF NOT EXISTS "Suppliers" (
                                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "company_name" VARCHAR NOT NULL,
                                           "contact_person" VARCHAR,
                                           "email" VARCHAR,
                                           "phone" VARCHAR,
                                           "address" TEXT,
                                           "delivery_time_days" INTEGER DEFAULT 7,
                                           "created_at" TIMESTAMP DEFAULT now()
    );

-- Orders Table
CREATE TABLE IF NOT EXISTS "Orders" (
                                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        "supplier_id" INTEGER,
                                        "order_date" TIMESTAMP NOT NULL,
                                        "expected_delivery_date" TIMESTAMP,
                                        "actual_delivery_date" TIMESTAMP,
                                        "status" VARCHAR,
                                        "total_amount" DECIMAL,
                                        "notes" TEXT,
                                        "created_at" TIMESTAMP DEFAULT now(),
    "updated_at" TIMESTAMP DEFAULT now()
    );
COMMENT ON COLUMN "Orders"."status" IS 'ENUM: ''ordered'', ''in_transit'', ''delivered'', ''cancelled''';

-- OrderItems Table
CREATE TABLE IF NOT EXISTS "OrderItems" (
                                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            "order_id" INTEGER,
                                            "part_id" INTEGER,
                                            "quantity" INTEGER NOT NULL,
                                            "unit_price" DECIMAL NOT NULL,
                                            "subtotal" DECIMAL NOT NULL
);

-- WorkOrders Table
CREATE TABLE IF NOT EXISTS "WorkOrders" (
                                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            "appointment_id" INTEGER,
                                            "mechanic_id" INTEGER,
                                            "start_time" TIMESTAMP,
                                            "end_time" TIMESTAMP,
                                            "work_description" TEXT,
                                            "parts_used" JSON,
                                            "actual_price" DECIMAL,
                                            "created_at" TIMESTAMP DEFAULT now()
    );

-- Calendar Table
CREATE TABLE IF NOT EXISTS "Calendar" (
                                          "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "date" DATE NOT NULL,
                                          "start_time" TIME NOT NULL,
                                          "end_time" TIME NOT NULL,
                                          "is_available" BOOLEAN DEFAULT true,
                                          "max_appointments" INTEGER DEFAULT 5,
                                          "current_appointments" INTEGER DEFAULT 0,
                                          "notes" TEXT
);

-- AppointmentHistory Table
CREATE TABLE IF NOT EXISTS "AppointmentHistory" (
                                                    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    "appointment_id" INTEGER,
                                                    "user_id" INTEGER,
                                                    "action" VARCHAR,
                                                    "old_status" VARCHAR,
                                                    "new_status" VARCHAR,
                                                    "comment" TEXT,
                                                    "created_at" TIMESTAMP DEFAULT now()
    );

-- PriceHistory Table
CREATE TABLE IF NOT EXISTS "PriceHistory" (
                                              "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "service_type" VARCHAR,
                                              "work_description" TEXT,
                                              "price" DECIMAL,
                                              "duration_minutes" INTEGER,
                                              "valid_from" TIMESTAMP NOT NULL,
                                              "valid_to" TIMESTAMP
);

-- Foreign Keys
ALTER TABLE "Vehicles" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");
ALTER TABLE "Appointments" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");
ALTER TABLE "Appointments" ADD FOREIGN KEY ("vehicle_id") REFERENCES "Vehicles" ("id");
ALTER TABLE "AppointmentMedia" ADD FOREIGN KEY ("appointment_id") REFERENCES "Appointments" ("id");
ALTER TABLE "Parts" ADD FOREIGN KEY ("supplier_id") REFERENCES "Suppliers" ("id");
ALTER TABLE "Orders" ADD FOREIGN KEY ("supplier_id") REFERENCES "Suppliers" ("id");
ALTER TABLE "OrderItems" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("id");
ALTER TABLE "OrderItems" ADD FOREIGN KEY ("part_id") REFERENCES "Parts" ("id");
ALTER TABLE "WorkOrders" ADD FOREIGN KEY ("appointment_id") REFERENCES "Appointments" ("id");
ALTER TABLE "WorkOrders" ADD FOREIGN KEY ("mechanic_id") REFERENCES "Users" ("id");
ALTER TABLE "AppointmentHistory" ADD FOREIGN KEY ("appointment_id") REFERENCES "Appointments" ("id");
ALTER TABLE "AppointmentHistory" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");
